name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.8"
          - "3.7"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install and run tests python ${{ matrix.python-version }}
        run: |
          pip install poetry
          poetry install
          poetry run flake8
          poetry run pylint national_memographic
          poetry run mypy national_memographic
          poetry run pytest
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: publish to PyPI
        run: |
          pip install poetry
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
