name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install and run tests
        run: |
          pip install poetry
          poetry install
          poetry run flake8
          poetry run pylint national_memographic
          poetry run mypy national_memographic
          poetry run pytest
